export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const GET_ALL_TODOS_ERROR = 'GET_ALL_TODOS_ERROR';

export const GET_USER_TODOS = 'GET_USER_TODOS';
export const GET_USER_TODOS_ERROR = 'GET_USER_TODOS_ERROR'

export const ADD_USER_TODO = 'ADD_USER_TODO';
export const ADD_USER_TODO_ERROR = 'ADD_USER_TODO_ERROR';

export const UPDATE_TODO_BY_ID = 'UPDATE_TODO_BY_ID';
export const UPDATE_TODO_BY_ID_ERROR = 'UPDATE_TODO_BY_ID_ERROR';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';